name = "Rusk"
grammar = "rusk"
path_suffixes = ["rsk", "rk"]
line_comments = ["// "]
tab_size = 4
autoclose_before = ";:.,=}])"
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
  { start = "'", end = "'", close = true, newline = false, not_in = ["string", "comment"] },
]
