use std::{
    env, fs,
    io::{self, IsTerminal, Read},
    path::{Path, PathBuf},
    process::{self, Command},
};

use rusk::{source_map_json, transpile};

const GENERATED_HEADER: &str = "// @generated by rusk; do not edit.\n";
const CARGO_WRAPPER_COMMANDS: &[&str] = &[
    "bench", "build", "check", "clippy", "doc", "fmt", "run", "test",
];

#[derive(Debug, Default)]
struct Args {
    input: Option<PathBuf>,
    output: Option<PathBuf>,
    source_map: Option<PathBuf>,
}

fn main() {
    match run(env::args().skip(1).collect()) {
        Ok(code) => process::exit(code),
        Err(error) => {
            eprintln!("rusk: {error}");
            process::exit(1);
        }
    }
}

fn run(raw_args: Vec<String>) -> Result<i32, Box<dyn std::error::Error>> {
    if is_cargo_wrapper_command(&raw_args) {
        return run_cargo_wrapper(raw_args);
    }

    let args = parse_args(raw_args)?;
    if args.input.is_none() && io::stdin().is_terminal() {
        print_help();
        return Ok(0);
    }

    let source = read_source(args.input.as_ref())?;
    let output = transpile(&source)?;

    if let Some(path) = args.output {
        fs::write(path, &output.rust)?;
    } else {
        print!("{}", &output.rust);
    }

    if let Some(path) = args.source_map {
        fs::write(path, source_map_json(&output))?;
    }

    Ok(0)
}

fn is_cargo_wrapper_command(raw_args: &[String]) -> bool {
    match raw_args.first().map(String::as_str) {
        Some("cargo") => true,
        Some(command) => CARGO_WRAPPER_COMMANDS.contains(&command),
        None => false,
    }
}

fn run_cargo_wrapper(raw_args: Vec<String>) -> Result<i32, Box<dyn std::error::Error>> {
    let cargo_args = if raw_args.first().is_some_and(|arg| arg == "cargo") {
        raw_args.into_iter().skip(1).collect::<Vec<_>>()
    } else {
        raw_args
    };

    let root = env::current_dir()?;
    let generated = transpile_cargo_sources(&root)?;
    let status = Command::new("cargo").args(&cargo_args).status();
    let cleanup = cleanup_generated_sources(&generated);

    if let Err(error) = cleanup {
        return Err(error);
    }

    Ok(status?.code().unwrap_or(1))
}

fn transpile_cargo_sources(root: &Path) -> Result<Vec<PathBuf>, Box<dyn std::error::Error>> {
    let mut sources = Vec::new();
    collect_rusk_sources(root, &mut sources)?;
    sources.sort();

    let mut generated = Vec::new();
    for source_path in sources {
        let rust_path = source_path.with_extension("rs");
        ensure_can_write_generated(&rust_path)?;
        let source = fs::read_to_string(&source_path)?;
        let output = transpile(&source)?;
        fs::write(&rust_path, format!("{GENERATED_HEADER}{}", output.rust))?;
        generated.push(rust_path);
    }

    Ok(generated)
}

fn collect_rusk_sources(
    root: &Path,
    sources: &mut Vec<PathBuf>,
) -> Result<(), Box<dyn std::error::Error>> {
    for path in cargo_source_roots(root) {
        if path.is_file() {
            if path.extension().is_some_and(|extension| extension == "rsk") {
                sources.push(path);
            }
        } else if path.is_dir() {
            collect_rusk_sources_in_dir(&path, sources)?;
        }
    }
    Ok(())
}

fn cargo_source_roots(root: &Path) -> Vec<PathBuf> {
    ["build.rsk", "src", "examples", "tests", "benches"]
        .into_iter()
        .map(|path| root.join(path))
        .collect()
}

fn collect_rusk_sources_in_dir(
    dir: &Path,
    sources: &mut Vec<PathBuf>,
) -> Result<(), Box<dyn std::error::Error>> {
    for entry in fs::read_dir(dir)? {
        let path = entry?.path();
        if path.is_dir() {
            collect_rusk_sources_in_dir(&path, sources)?;
        } else if path.extension().is_some_and(|extension| extension == "rsk") {
            sources.push(path);
        }
    }
    Ok(())
}

fn ensure_can_write_generated(path: &Path) -> Result<(), Box<dyn std::error::Error>> {
    if !path.exists() {
        return Ok(());
    }

    let existing = fs::read_to_string(path)?;
    if existing.starts_with(GENERATED_HEADER) {
        Ok(())
    } else {
        Err(format!(
            "refusing to overwrite non-generated Rust file: {}",
            path.display()
        )
        .into())
    }
}

fn cleanup_generated_sources(paths: &[PathBuf]) -> Result<(), Box<dyn std::error::Error>> {
    for path in paths {
        if !path.exists() {
            continue;
        }
        let existing = fs::read_to_string(path)?;
        if existing.starts_with(GENERATED_HEADER) {
            fs::remove_file(path)?;
        }
    }
    Ok(())
}

fn parse_args(raw_args: Vec<String>) -> Result<Args, String> {
    let mut args = Args::default();
    let mut index = 0usize;
    let raw_args = if raw_args.first().is_some_and(|arg| arg == "transpile") {
        raw_args.into_iter().skip(1).collect::<Vec<_>>()
    } else {
        raw_args
    };

    while index < raw_args.len() {
        match raw_args[index].as_str() {
            "-h" | "--help" => {
                print_help();
                process::exit(0);
            }
            "-o" | "--output" => {
                index += 1;
                let Some(value) = raw_args.get(index) else {
                    return Err("--output requires a path".to_string());
                };
                args.output = Some(PathBuf::from(value));
            }
            "--source-map" => {
                index += 1;
                let Some(value) = raw_args.get(index) else {
                    return Err("--source-map requires a path".to_string());
                };
                args.source_map = Some(PathBuf::from(value));
            }
            value if value.starts_with('-') => return Err(format!("unknown option: {value}")),
            value => {
                if args.input.is_some() {
                    return Err("only one input path is supported".to_string());
                }
                args.input = Some(PathBuf::from(value));
            }
        }
        index += 1;
    }

    Ok(args)
}

fn read_source(path: Option<&PathBuf>) -> Result<String, Box<dyn std::error::Error>> {
    match path {
        Some(path) => Ok(fs::read_to_string(path)?),
        None => {
            let mut source = String::new();
            io::stdin().read_to_string(&mut source)?;
            Ok(source)
        }
    }
}

fn print_help() {
    println!(
        "rusk - indentation-based Rust syntax transpiler\n\nUSAGE:\n    rusk [transpile] [INPUT.rsk] [-o OUTPUT.rs] [--source-map SOURCE_MAP]\n    rusk [cargo] <CARGO_COMMAND> [CARGO_ARGS...]\n\nCargo wrapper commands transpile Cargo source roots (*.rsk under src, examples, tests, benches, and build.rsk) to temporary generated .rs files, run cargo, then remove generated files.\n\nExamples:\n    rusk run\n    rusk cargo test\n\nIf INPUT is omitted, rusk reads Rusk source from stdin when stdin is piped; otherwise it prints this help."
    );
}

#[cfg(test)]
mod tests {
    use super::*;

    fn temp_project(name: &str) -> PathBuf {
        let path = env::temp_dir().join(format!("rusk-{name}-{}", process::id()));
        let _ = fs::remove_dir_all(&path);
        fs::create_dir_all(path.join("src")).unwrap();
        fs::write(
            path.join("Cargo.toml"),
            "[package]\nname = \"rusk-wrapper-test\"\nversion = \"0.1.0\"\nedition = \"2024\"\n",
        )
        .unwrap();
        path
    }

    #[test]
    fn transpiles_cargo_sources_to_generated_rust() {
        let project = temp_project("cargo-sources");
        fs::write(
            project.join("src/main.rsk"),
            "pub fn main() =\n    println!(\"hello\")\n",
        )
        .unwrap();

        let generated = transpile_cargo_sources(&project).unwrap();
        assert_eq!(generated, vec![project.join("src/main.rs")]);
        let rust = fs::read_to_string(project.join("src/main.rs")).unwrap();
        assert!(rust.starts_with(GENERATED_HEADER));
        assert!(rust.contains("println!(\"hello\");"));

        cleanup_generated_sources(&generated).unwrap();
        assert!(!project.join("src/main.rs").exists());
        let _ = fs::remove_dir_all(project);
    }

    #[test]
    fn refuses_to_overwrite_non_generated_rust() {
        let project = temp_project("cargo-conflict");
        fs::write(project.join("src/main.rsk"), "pub fn main() = 1\n").unwrap();
        fs::write(project.join("src/main.rs"), "fn main() {}\n").unwrap();

        let error = transpile_cargo_sources(&project).unwrap_err().to_string();
        assert!(error.contains("refusing to overwrite non-generated Rust file"));
        let _ = fs::remove_dir_all(project);
    }
}
