use std::{
    env, fs,
    io::{self, IsTerminal, Read},
    path::{Path, PathBuf},
    process::{self, Command},
};

use rusk::{
    FormatOptions, SourceSyntax, format_source, ruk_to_rust, rusk_to_ruk, rust_to_ruk,
    rust_to_rusk, source_map_json, to_rust, transpile,
};

const GENERATED_HEADER: &str = "// @generated by rusk; do not edit.\n";
const CARGO_WRAPPER_COMMANDS: &[&str] =
    &["bench", "build", "check", "clippy", "doc", "run", "test"];

#[derive(Debug)]
struct Args {
    input: Option<PathBuf>,
    output: Option<PathBuf>,
    source_map: Option<PathBuf>,
    format: bool,
    reverse: bool,
    to_ruk: bool,
    line_width: usize,
}

impl Default for Args {
    fn default() -> Self {
        Self {
            input: None,
            output: None,
            source_map: None,
            format: false,
            reverse: false,
            to_ruk: false,
            line_width: FormatOptions::default().line_width,
        }
    }
}

fn main() {
    match run(env::args().skip(1).collect()) {
        Ok(code) => process::exit(code),
        Err(error) => {
            eprintln!("rusk: {error}");
            process::exit(1);
        }
    }
}

fn run(raw_args: Vec<String>) -> Result<i32, Box<dyn std::error::Error>> {
    if is_cargo_wrapper_command(&raw_args) {
        return run_cargo_wrapper(raw_args);
    }

    let args = parse_args(raw_args)?;
    if args.input.is_none() && io::stdin().is_terminal() {
        print_help();
        return Ok(0);
    }

    let source = read_source(args.input.as_ref())?;
    if args.format {
        if args.source_map.is_some() {
            return Err("--source-map is not supported with fmt".into());
        }
        let syntax = source_syntax(args.input.as_deref());
        let formatted = if syntax == SourceSyntax::Ruk {
            rust_to_ruk(&ruk_to_rust(&source)?)?
        } else {
            format_source(
                &source,
                FormatOptions {
                    line_width: args.line_width,
                },
            )?
        };
        if let Some(path) = args.output {
            fs::write(path, &formatted)?;
        } else {
            print!("{}", &formatted);
        }
        return Ok(0);
    }

    if args.reverse || args.to_ruk {
        if args.source_map.is_some() {
            return Err("--source-map is not supported with syntax conversion".into());
        }
        let converted = if args.to_ruk {
            match source_syntax(args.input.as_deref()) {
                SourceSyntax::Rusk => rusk_to_ruk(&source)?,
                SourceSyntax::Ruk => ensure_cli_trailing_newline(&source),
                SourceSyntax::Rust => rust_to_ruk(&source)?,
            }
        } else {
            rust_to_rusk(&source)?
        };
        if let Some(path) = args.output {
            fs::write(path, &converted)?;
        } else {
            print!("{}", &converted);
        }
        return Ok(0);
    }

    let syntax = source_syntax(args.input.as_deref());
    let output = if syntax == SourceSyntax::Rusk {
        transpile(&source)?
    } else {
        rusk::TranspileOutput {
            rust: to_rust(&source, syntax)?,
            source_map: Vec::new(),
            source_tree: Vec::new(),
        }
    };

    if let Some(path) = args.output {
        fs::write(path, &output.rust)?;
    } else {
        print!("{}", &output.rust);
    }

    if let Some(path) = args.source_map {
        fs::write(path, source_map_json(&output))?;
    }

    Ok(0)
}

fn is_cargo_wrapper_command(raw_args: &[String]) -> bool {
    match raw_args.first().map(String::as_str) {
        Some("cargo") => true,
        Some(command) => CARGO_WRAPPER_COMMANDS.contains(&command),
        None => false,
    }
}

fn run_cargo_wrapper(raw_args: Vec<String>) -> Result<i32, Box<dyn std::error::Error>> {
    let cargo_args = if raw_args.first().is_some_and(|arg| arg == "cargo") {
        raw_args.into_iter().skip(1).collect::<Vec<_>>()
    } else {
        raw_args
    };

    let root = env::current_dir()?;
    transpile_cargo_sources(&root)?;
    let status = Command::new("cargo").args(&cargo_args).status();

    Ok(status?.code().unwrap_or(1))
}

fn transpile_cargo_sources(root: &Path) -> Result<Vec<PathBuf>, Box<dyn std::error::Error>> {
    let mut sources = Vec::new();
    collect_rusk_sources(root, &mut sources)?;
    sources.sort();

    let mut generated = Vec::new();
    for source_path in sources {
        let rust_path = source_path.with_extension("rs");
        let source = fs::read_to_string(&source_path)?;
        let rust_source = to_rust(&source, source_syntax(Some(&source_path)))?;
        let rust = format!("{GENERATED_HEADER}{rust_source}");
        write_generated_source(&rust_path, &rust)?;
        generated.push(rust_path);
    }

    Ok(generated)
}

fn collect_rusk_sources(
    root: &Path,
    sources: &mut Vec<PathBuf>,
) -> Result<(), Box<dyn std::error::Error>> {
    for path in cargo_source_roots(root) {
        if path.is_file() {
            if is_transpilable_source(&path) {
                sources.push(path);
            }
        } else if path.is_dir() {
            collect_rusk_sources_in_dir(&path, sources)?;
        }
    }
    Ok(())
}

fn cargo_source_roots(root: &Path) -> Vec<PathBuf> {
    [
        "build.rsk",
        "build.rk",
        "src",
        "examples",
        "tests",
        "benches",
    ]
    .into_iter()
    .map(|path| root.join(path))
    .collect()
}

fn collect_rusk_sources_in_dir(
    dir: &Path,
    sources: &mut Vec<PathBuf>,
) -> Result<(), Box<dyn std::error::Error>> {
    for entry in fs::read_dir(dir)? {
        let path = entry?.path();
        if path.is_dir() {
            collect_rusk_sources_in_dir(&path, sources)?;
        } else if is_transpilable_source(&path) {
            sources.push(path);
        }
    }
    Ok(())
}

fn is_transpilable_source(path: &Path) -> bool {
    path.extension()
        .and_then(|extension| extension.to_str())
        .is_some_and(|extension| matches!(extension, "rsk" | "rk"))
}

fn write_generated_source(path: &Path, rust: &str) -> Result<(), Box<dyn std::error::Error>> {
    if path.exists() {
        let existing = fs::read_to_string(path)?;
        if !existing.starts_with(GENERATED_HEADER) {
            return Err(format!(
                "refusing to overwrite non-generated Rust file: {}",
                path.display()
            )
            .into());
        }
        if existing == rust {
            return Ok(());
        }
    }

    fs::write(path, rust)?;
    Ok(())
}

fn parse_args(raw_args: Vec<String>) -> Result<Args, String> {
    let mut args = Args::default();
    let mut index = 0usize;
    let raw_args = if raw_args.first().is_some_and(|arg| {
        matches!(
            arg.as_str(),
            "transpile" | "fmt" | "format" | "from-rust" | "to-rusk" | "to-ruk" | "from-rusk"
        )
    }) {
        args.format = raw_args
            .first()
            .is_some_and(|arg| arg == "fmt" || arg == "format");
        args.reverse = raw_args
            .first()
            .is_some_and(|arg| arg == "from-rust" || arg == "to-rusk");
        args.to_ruk = raw_args
            .first()
            .is_some_and(|arg| arg == "to-ruk" || arg == "from-rusk");
        raw_args.into_iter().skip(1).collect::<Vec<_>>()
    } else {
        raw_args
    };

    while index < raw_args.len() {
        match raw_args[index].as_str() {
            "-h" | "--help" => {
                print_help();
                process::exit(0);
            }
            "-o" | "--output" => {
                index += 1;
                let Some(value) = raw_args.get(index) else {
                    return Err("--output requires a path".to_string());
                };
                args.output = Some(PathBuf::from(value));
            }
            "--source-map" => {
                index += 1;
                let Some(value) = raw_args.get(index) else {
                    return Err("--source-map requires a path".to_string());
                };
                args.source_map = Some(PathBuf::from(value));
            }
            "--line-width" => {
                index += 1;
                let Some(value) = raw_args.get(index) else {
                    return Err("--line-width requires a number".to_string());
                };
                args.line_width = value
                    .parse()
                    .map_err(|_| "--line-width requires a number".to_string())?;
            }
            value if value.starts_with('-') => return Err(format!("unknown option: {value}")),
            value => {
                if args.input.is_some() {
                    return Err("only one input path is supported".to_string());
                }
                args.input = Some(PathBuf::from(value));
            }
        }
        index += 1;
    }

    Ok(args)
}

fn read_source(path: Option<&PathBuf>) -> Result<String, Box<dyn std::error::Error>> {
    match path {
        Some(path) => Ok(fs::read_to_string(path)?),
        None => {
            let mut source = String::new();
            io::stdin().read_to_string(&mut source)?;
            Ok(source)
        }
    }
}

fn source_syntax(path: Option<&Path>) -> SourceSyntax {
    match path
        .and_then(Path::extension)
        .and_then(|extension| extension.to_str())
    {
        Some("rk") => SourceSyntax::Ruk,
        Some("rs") => SourceSyntax::Rust,
        _ => SourceSyntax::Rusk,
    }
}

fn ensure_cli_trailing_newline(source: &str) -> String {
    if source.ends_with('\n') {
        source.to_string()
    } else {
        format!("{source}\n")
    }
}

fn print_help() {
    println!(
        "rusk - indentation-based Rust syntax transpiler\n\nUSAGE:\n    rusk [transpile] [INPUT.rsk|INPUT.rk] [-o OUTPUT.rs] [--source-map SOURCE_MAP]\n    rusk from-rust [INPUT.rs] [-o OUTPUT.rsk]\n    rusk to-ruk [INPUT.rs|INPUT.rsk] [-o OUTPUT.rk]\n    rusk fmt [INPUT.rsk|INPUT.rk] [-o INPUT] [--line-width N]\n    rusk [cargo] <CARGO_COMMAND> [CARGO_ARGS...]\n\nCargo wrapper commands transpile Cargo source roots (*.rsk and *.rk under src, examples, tests, benches, plus build.rsk/build.rk) to cached generated .rs files, then run cargo.\n\nExamples:\n    rusk from-rust src/main.rs -o src/main.rsk\n    rusk to-ruk src/main.rs -o src/main.rk\n    rusk fmt src/main.rsk -o src/main.rsk\n    rusk run\n    rusk cargo fmt\n    rusk cargo test\n\nIf INPUT is omitted, rusk reads source from stdin when stdin is piped; otherwise it prints this help."
    );
}

#[cfg(test)]
mod tests {
    use super::*;

    fn temp_project(name: &str) -> PathBuf {
        let path = env::temp_dir().join(format!("rusk-{name}-{}", process::id()));
        let _ = fs::remove_dir_all(&path);
        fs::create_dir_all(path.join("src")).unwrap();
        fs::write(
            path.join("Cargo.toml"),
            "[package]\nname = \"rusk-wrapper-test\"\nversion = \"0.1.0\"\nedition = \"2024\"\n",
        )
        .unwrap();
        path
    }

    #[test]
    fn transpiles_cargo_sources_to_cached_generated_rust() {
        let project = temp_project("cargo-sources");
        let source_path = project.join("src/main.rsk");
        let rust_path = project.join("src/main.rs");
        fs::write(&source_path, "pub fn main() =\n    println!(\"hello\")\n").unwrap();

        let generated = transpile_cargo_sources(&project).unwrap();
        assert_eq!(generated, vec![rust_path.clone()]);
        let rust = fs::read_to_string(&rust_path).unwrap();
        assert!(rust.starts_with(GENERATED_HEADER));
        assert!(rust.contains("println!(\"hello\");"));

        let mut permissions = fs::metadata(&rust_path).unwrap().permissions();
        permissions.set_readonly(true);
        fs::set_permissions(&rust_path, permissions).unwrap();
        let generated = transpile_cargo_sources(&project).unwrap();
        assert_eq!(generated, vec![rust_path.clone()]);

        let mut permissions = fs::metadata(&rust_path).unwrap().permissions();
        permissions.set_readonly(false);
        fs::set_permissions(&rust_path, permissions).unwrap();
        fs::write(&source_path, "pub fn main() =\n    println!(\"cached\")\n").unwrap();
        let generated = transpile_cargo_sources(&project).unwrap();
        assert_eq!(generated, vec![rust_path.clone()]);
        let rust = fs::read_to_string(&rust_path).unwrap();
        assert!(rust.starts_with(GENERATED_HEADER));
        assert!(rust.contains("println!(\"cached\");"));

        let _ = fs::remove_dir_all(project);
    }

    #[test]
    fn transpiles_ruk_cargo_sources_to_cached_generated_rust() {
        let project = temp_project("cargo-ruk-sources");
        let source_path = project.join("src/main.rk");
        let rust_path = project.join("src/main.rs");
        fs::write(
            &source_path,
            "pub fn main() {\n    println!(\"hello\")\n}\n",
        )
        .unwrap();

        let generated = transpile_cargo_sources(&project).unwrap();
        assert_eq!(generated, vec![rust_path.clone()]);
        let rust = fs::read_to_string(&rust_path).unwrap();
        assert!(rust.starts_with(GENERATED_HEADER));
        assert!(rust.contains("println!(\"hello\");"));
        let _ = fs::remove_dir_all(project);
    }

    #[test]
    fn refuses_to_overwrite_non_generated_rust() {
        let project = temp_project("cargo-conflict");
        fs::write(project.join("src/main.rsk"), "pub fn main() = 1\n").unwrap();
        fs::write(project.join("src/main.rs"), "fn main() {}\n").unwrap();

        let error = transpile_cargo_sources(&project).unwrap_err().to_string();
        assert!(error.contains("refusing to overwrite non-generated Rust file"));
        let _ = fs::remove_dir_all(project);
    }
}
